# Generated by Django 5.2.11 on 2026-02-13 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sport_name', models.CharField(max_length=100)),
                ('Sport_description', models.CharField(max_length=400)),
                ('Sport_img1', models.ImageField(upload_to='Category_image')),
                ('Sport_img2', models.ImageField(upload_to='Category_image')),
            ],
        ),
    ]
