# Generated by Django 5.2.11 on 2026-02-21 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0002_categorydb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cityname', models.CharField(max_length=100)),
            ],
        ),
    ]
