# Generated by Django 5.2.11 on 2026-02-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Turf_name', models.CharField(max_length=100)),
                ('Sport', models.CharField(max_length=100)),
                ('Owner', models.CharField()),
                ('City', models.CharField()),
                ('Location', models.CharField(max_length=300)),
                ('Price_per_hour', models.IntegerField()),
                ('Description', models.CharField(max_length=400)),
                ('Size', models.CharField(max_length=50)),
                ('Turf_image1', models.ImageField(upload_to='turfs_image')),
                ('Turf_image2', models.ImageField(upload_to='turfs_image')),
            ],
        ),
    ]
