# Generated by Django 5.2.11 on 2026-02-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Owner_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Turf',
            new_name='TurfDb',
        ),
    ]
