# Generated by Django 5.2.11 on 2026-02-25 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdb',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
