# Generated by Django 5.2.11 on 2026-03-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0003_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TurfOwnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('owner_name', models.CharField(max_length=150)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_phone', models.CharField(max_length=15)),
                ('turf_name', models.CharField(max_length=150)),
                ('turf_city', models.CharField(max_length=100)),
                ('turf_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
