# Generated by Django 5.2.11 on 2026-03-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_turfownerapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingdb',
            name='user_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
